; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l4r5zi]
platform = ststm32
board = nucleo_l4r5zi
framework = stm32cube

; Serial Monitor options
monitor_speed = 115200

; 1. Tell PlatformIO you are debugging
build_type = debug

; 2. Strip the default size optimization flag
build_unflags = -Os

; 3. Force no optimization (-O0) and max debug symbols (-g3)
build_flags = 
    -O0 
    -g3
    -Wl,-u,_printf_float
    -I FATFS/App
    -I FATFS/Target
    -I Middlewares/Third_Party/FatFs/src
    

build_src_filter = 
    +<*>
    +<../FATFS/App>
    +<../FATFS/Target>
    +<../Middlewares/Third_Party/FatFs/src>
    